### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by lordmorgul** [W5DMH/commstatx#1]
This results in core dump and shutdown during the initial read of directed.txt.  Resetting data does not fix it, neither does replacing the config, copy of directed,  or the db3 files from the repo back into local directory before running.

Fedora 37, Python 3.11.1

```
Traceback (most recent call last):
  File "/home/andrew/commstatx/commstatx.py", line 633, in directed
    self.loadbulletins()
  File "/home/andrew/commstatx/commstatx.py", line 827, in loadbulletins
    result = connection.execute(query, (selectedgroup,))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked
```

**Comment by W5DMH** [comment]
It sounds like maybe a zombie process is still running in the background and it has a database lock, If you don't know how to chase a zombie process then a reboot would be the answer.

**Comment by lordmorgul** [comment]
I know you have a backlog of items to work, so will be trying to dig into this myself, but if anyone else is seeing it happen other than me that is a clue it isn't just the software versions I have.

I think the core dump and the traceback on locked database might actually be separable things, but I'm not sure what the core dump trigger is then.  Sometimes the app runs for minutes, somethings almost an hour, has new traffic come in or not, and still eventually core dumps.  The system is not memory or process overloaded, especially right after reboots. (Apple Macbook Pro 2015 Core i7, Fedora Linux 37)

There was no zombie process when this occurs, I did check for it before launch and after crash. I suspected it was the database lock not getting cleared when a crash had previously happened, but it is odd that it does not happen immediately after starting the datareader but about half way through spamming the output of the read.  It is not always on the same call/message, or at the same database access in the code.  I have seen it happen several times through the read, or once.  By the time the datareader finishes output there are core dump message and GUI terminates.  This suggests it is transient and possibly a multi-thread issue.

```
sqlite3 --version
3.40.0 2022-11-16

python3-3.11.1-3.fc37.x86_64
sqlite-libs-3.40.0-1.fc37.x86_64
sqlite-3.40.0-1.fc37.x86_64
python3-aiosqlite-0.17.0-6.fc37.noarch
python3-databases+sqlite-0.7.0-1.fc37.noarch
sqlite-tools-3.40.0-1.fc37.x86_64
sqlite-doc-3.40.0-1.fc37.noarch
sqliteman-1.2.2-33.fc37.x86_64
```

It shows up at this location in code also:
```
Traceback (most recent call last):
  File "/home/andrew/commstatx/./commstatx.py", line 945, in nextNews
    self.feed()                             # start again
    ^^^^^^^^^^^
  File "/home/andrew/commstatx/./commstatx.py", line 898, in feed
    result = connection.execute(query, (selectedgroup,))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked
```

And also here:
```
Traceback (most recent call last):
  File "/home/andrew/commstatx-amrron/commstatx.py", line 634, in directed
    self.loadData()
  File "/home/andrew/commstatx-amrron/commstatx.py", line 542, in loadData
    result = connection.execute(query,(selectedgroup,))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked
```

I'm seeing a core dump still occur after removing the traffic.db3, copyDIRECTED.TXT, callarchive.db3, and __pychache__, then replacing the db3 files from the git repo.  Also performed the 'data reset' function within commstat and have the same result.

After fresh reboot, then commstatx.py is started, and has locked db tracebacks (on fresh copy of db3 files from git), but datareader is loading my DIRECTED.TXT, and then it core dumps, these calls return nothing (no hung process using the file):
-> lsof traffic.db3
-> lsof callarchive.db3
-> fuser callarchive.db3 
-> fuser traffic.db3

$-> sqlite3 callarchive.db3 "pragma integrity_check;"
ok

$-> sqlite3 traffic.db3 "pragma integrity_check;"
ok

All files are local, so not a network file issue.

So it is not a hung process, or a faulty database file.  Best I can tell is it might be a multi-threaded read while write locked?  The core dump I have no ideas yet.

A couple useful discussion links:
https://stackoverflow.com/questions/151026/how-do-i-unlock-a-sqlite-database
https://www2.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked
https://stackoverflow.com/questions/2740806/python-sqlite-database-is-locked

Ideas:

> I was having "database is locked" errors in a multi-threaded application as well, which appears to be the SQLITE_BUSY result code, and I solved it with setting sqlite3_busy_timeout to something suitably long like 30000.

> The database is locked by another process that is writing to it. You have to wait until the other transaction is committed. See the documentation of connect()

> when I just had one writer and one reader, my issue was that one of the reads was taking too long: longer than the stipulated timeout of 5 seconds. So the writer timed out and caused the error.
> So, be careful when reading all entries from a database especially from one which the size of the table grows over time.

**Comment by lordmorgul** [comment]
Minor typo in commstatx:895 query, no space after SELECT does not seem to make the query fail though.

`query = "SELECT* FROM marquees_data WHERE groupname = ? ORDER BY date DESC LIMIT 1"`
`query = "SELECT * FROM marquees_data WHERE groupname = ? ORDER BY date DESC LIMIT 1"`

**Comment by W5DMH** [comment]
So the database locks can happen if the datareader thread is still open (called by a Directed.txt file size change so it is very intermittent) and for some reason does not close before another parsing cycle occurs. Currently I am not thread tracking (not opening a new thread until the previous thread is closed) but it is very odd that you get it so consistently. I have not tested with Fedora or Python 3.11 but I doubt either is causing the issue you are seeing.

**Comment by lordmorgul** [comment]
I had a fairly large DIRECTED.TXT when first trying commstatx, but the data reset moved that to backup and working with one that is currently 582k.  I also tried with just 30 recent messages from DIRECTED.TXT (now 2k) into a new file, and the locked database errors still occur when it only has 30 recent messages to read on startup, so **probably not related to the total runtime of Datareader itself**.

For testing I'm running from a script now saved as ~/bin/commstatx:
```
cd /home/andrew/commstatx

sqlite3 traffic.db3 "pragma integrity_check;"
sqlite3 callarchive.db3 "pragma integrity_check;"
fuser traffic.db3
fuser callarchive.db3 
lsof callarchive.db3
lsof traffic.db3

python3 commstatx.py
```

`/home/andrew/bin/commstat: line 10: 195990 Aborted                 (core dumped) python3 commstatx.py`

The datareader apparently keeps running after the core dump message shows up:
`/home/andrew/bin/commstat: line 10: 195990 Aborted                 (core dumped) python3 commstatx.py`
`Datareader stopped :2023-02-02 20:42:20`

However, there is at least an **associated trigger** in a new run of datareader when a newer message arrived causing the core dump while datareader is going.  App runs fine until then, so my observations that it is random may be wrong and it is just different timing of new messages coming in.

If I launch the script twice on purpose the checks on processes using the db3 files shows them, so that is working to detect hung processes.
```
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF      NODE NAME
python3 196378 andrew    5u   REG  253,1 53231616 100608340 callarchive.db3
python3 196378 andrew    8u   REG  253,1 53231616 100608340 callarchive.db3
python3 196378 andrew   10u   REG  253,1 53231616 100608340 callarchive.db3
python3 196378 andrew   13u   REG  253,1 53231616 100608340 callarchive.db3
python3 196378 andrew   16u   REG  253,1 53231616 100608340 callarchive.db3
python3 196378 andrew   18u   REG  253,1 53231616 100608340 callarchive.db3
python3 196378 andrew   21u   REG  253,1 53231616 100608340 callarchive.db3
python3 196378 andrew   24u   REG  253,1 53231616 100608340 callarchive.db3

COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF      NODE NAME
python3 196311 andrew   83u   REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew    3uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew    6uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew    7uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew    9uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   11uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   12uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   14uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   15uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   17uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   19uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   20uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   22uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   23uw  REG  253,1   118784 100608346 traffic.db3
python3 196378 andrew   25uw  REG  253,1   118784 100608346 traffic.db3

[2] 196409
Error: in prepare, database is locked (5)

```
The second script exits early detecting locked database, this seems good.  The first launched one continues until core dump and has the intermittent locked database errors.

The app opens and displays data for a short time until core dump.   I get a bad message warning on every single item in DIRECTED.TXT, not sure if this is still normal.  These display while the messages visually seem well formed, and sometimes are the correct group, and are generated by commstat sitrep.

```
Failed Commstatx msg criteria, incorrect group or possibly not a Commstatx msg
Failed Commstatx criteria, probably not a Commstatx msg

```

**Comment by W5DMH** [comment]
Each failed message is preceded by the actual string that failed. Is the preceding message a valid message that Commstat should have parsed? 
Typically you will get the red messages when it is a group snr or some other non-Commstat message. 
Did yours act this way from the install? Or did it behave for a while (days) and then started acting up with the database lock?

**Comment by lordmorgul** [comment]
Yes commstat sourced messages seem to fail processing, it may be just some character badly decoded though.  Here is an example in my copyDIRECTED.txt that says failed when datareader parses it, with sender callsign at front end removed.  This appears to be well formed?
 "@CSTAT  ,EM63,1,904,111111111111,NOTHING BUT SUNSHINE FOR THE DAY,{&%} ♢"

I don't recall if it really behaved better at first, I think not, but I have one statrep that did parse right, and I can now keep it open for at least today without core dump, so a python or library update must have changed something; Fedora does rapidly change.

It now hangs when I try to Transmit statrep and has to be killed.  But when I save a statrep it is showing as saved so I'll leave it open and see what happens with it.

**Comment by lordmorgul** [comment]
v0.093 is stable all day and processing all the messages I thought it couldn't...

I changed my preferences group order, setting @CSTAT active group as "group 2" rather than group 1, restarted it a few times, and no core dumps.  I'm pretty sure an OS update fixed that issue, since I think this is the same version I had when I posted this issue thread.  The message parsing, not sure... maybe the group order change, but that is odd and could have been the OS update too.

Is the issue with python hanging when clicking statrep transmit a new one to you?  Still have that for both Forward Transmit and Transmit.

**Comment by lordmorgul** [comment]
v0.096 corrects the transmit hang issue, still a large enough lag between clicking transmit and js8call accepting the message into outgoing msg field, so that sometimes gnome shows the hung app "force quit" / "wait" dialog, but it does succeed now.  I assume the lag there is normal.
Thanks for all the work and dealing with various inputs like mine about it!  Fedora 37 x64 as of 20230218 working for commstatx v0.096.
